version: "3.6" 

services:
  # Framework for data visualization
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:9.1.8
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - murat_network
      - murat_db
      - kafka_network
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeperritha
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - murat_network
      - murat_db
      - kafka_network

  kafka1:
    image: bitnami/kafka:3.3.1
    container_name: kafkaritha
    ports:
      - '9093:9093'
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - murat_network
      - murat_db
      - kafka_network

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdropritha
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka1:9092
    depends_on:
      - kafka1
    networks:
      - murat_network
      - murat_db
      - kafka_network

  influxdb:
    image: influxdb:latest
    container_name: influxdbritha
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    depends_on:
      - zookeeper
      - kafka1
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: Rahma
      DOCKER_INFLUXDB_INIT_PASSWORD: rahma1234
      DOCKER_INFLUXDB_INIT_ORG: OstProject
      DOCKER_INFLUXDB_INIT_BUCKET: BloodPressure
    networks:
      - murat_network
      - murat_db
      - kafka_network

  # telegraf:
  #   image: telegraf:latest
  #   container_name: telegrafritha
  #   depends_on:
  #     - zookeeper
  #     - influxdb
  #     - kafka1
  #   restart: unless-stopped
  #   networks:
  #     - murat_network
  #     - murat_db
  #     - kafka_network
  #   volumes:
  #     - C:/Users/DELL5490/Desktop/Master2/kafera/kafera/islam.conf:/etc/telegraf/telegraf.conf:ro


      
networks:
  murat_db:
    driver: bridge

  kafka_network:
    driver: bridge

  murat_network:
    driver: bridge