{
 "title": "Voting Classifier and Count Sketch",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "High BloodPressure count of Diffusion Flow",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Counter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Hypertension_Stage_1\" or r[\"_field\"] == \"Hypertension_Stage_2\" or r[\"_field\"] == \"Hypertensive_Crisis\" or r[\"_field\"] == \"Elevated\")"
    },
    {}
   ]
  },
  {
   "title": "SBP Tracking",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"classModel\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SBP\")\r\n"
    }
   ]
  },
  {
   "title": "DBP tracking",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"classModel\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DBP\")\r\n"
    }
   ]
  },
  {
   "title": "Predicted CLASS :  0=Normal 1=High",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"classModel\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Predicted_Class\")"
    }
   ]
  },
  {
   "title": "TRUE CLASS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"classModel\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"True_Class\")"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"classModel\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"CO\" or r[\"_field\"] == \"HR\" or r[\"_field\"] == \"MAP\" or r[\"_field\"] == \"PP\" or r[\"_field\"] == \"RR\" or r[\"_field\"] == \"SPO2\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"classModel\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Wrong Classifications\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"classModel\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Correct Classifications\")"
    }
   ]
  }
 ]
}