{
 "title": "KMeans_AnomalyDetection",
 "time": { "from": "2023-12-19T17:34:43.636Z", "to": "2023-12-19T17:34:48.044Z" },
 "panels": [
  {
   "title": "Anomaly Detected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"KMeans\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"prediction\")\r\n  |> yield(name: \"raw\")"
    }
   ]
  },
  {
   "title": "Last SBP and DBP values",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"KMeans\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SBP\" or r[\"_field\"] == \"DBP\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Maximum DBP and SBP values",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"KMeans\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SBP\" or r[\"_field\"] == \"DBP\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Systolic and Diastolic Blood Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"KMeans\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DBP\" or r[\"_field\"] == \"SBP\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Anomaly detected by KMeans Clustering",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"KMeans\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"prediction\")\r\n  |> yield(name: \"raw\")"
    }
   ]
  }
 ]
}