{
 "title": "Blood Pressure",
 "time": { "from": "2023-12-19T12:40:40.371Z", "to": "2023-12-19T12:40:45.987Z" },
 "panels": [
  {
   "title": "Anomaly Detected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IsolationForestv4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Detection\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Systolic Blood Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IsolationForestv4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SBP\")\r\n  |> yield(name: \"raw\")"
    }
   ]
  },
  {
   "title": "Diastolic Blood Pressure ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IsolationForestv4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DBP\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IsolationForestv4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"HR\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cardiac Output ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "flowmlpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IsolationForestv4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"CO\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Respiratory Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IsolationForestv4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Blood Pressure Streaming",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IsolationForestv4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DBP\" or r[\"_field\"] == \"SBP\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IsolationForestv4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"HR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Anomaly detected by Isolation Forest",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IsolationForestv4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Detection\")\r\n  |> yield(name: \"raw\")"
    }
   ]
  },
  {
   "title": "Percentage of Anomalies in Total Records",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IsolationForestv4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"All records\" or r[\"_field\"] == \"Detection\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}