{
 "title": "Blood Pressure Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "DIASTOLIC BLOOD PRESSURE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Actual_SBP_DBP\" and r[\"_field\"] == \"DBP\")\r\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Current SBP",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Actual_SBP_DBP\" and r[\"_field\"] == \"SBP\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Current DBP",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Actual_SBP_DBP\" and r[\"_field\"] == \"DBP\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Expected SBP after 15 mins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Forecast_15\" and r[\"_field\"] == \"SBP\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Expected DBP after 15 mins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Forecast_15\" and r[\"_field\"] == \"DBP\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "SYSTOLIC BLOOD PRESSURE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Actual_SBP_DBP\" and r[\"_field\"] == \"SBP\")\r\n  |> sort(columns: [\"_time\"])\r\n\r\n"
    }
   ]
  },
  {
   "title": "Expected  SBP after 30 mins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Forecast_30\" and r[\"_field\"] == \"SBP\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Expected DBP after 30 min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BloodPressure\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Forecast_30\" and r[\"_field\"] == \"DBP\")\r\n  |> last()\r\n"
    }
   ]
  }
 ]
}