{
 "title": "Oxygen Saturation Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Oxygen Saturation Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Monitoring_SPO2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SPO2_Monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SPO2\")\r\n  |> yield(name: \"actual_values\")\r\n"
    }
   ]
  },
  {
   "title": "max SPO2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Monitoring_SPO2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SPO2_Monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SPO2\")\r\n  |> max()\r\n  |> yield(name: \"max_spo2\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "avg SPO2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Monitoring_SPO2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SPO2_Monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SPO2\")\r\n  |> mean()\r\n  |> yield(name: \"avg_spo2\")\r\n"
    }
   ]
  },
  {
   "title": "min SPO2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Monitoring_SPO2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SPO2_Monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SPO2\")\r\n  |> min()\r\n  |> yield(name: \"min_spo2\")\r\n"
    }
   ]
  },
  {
   "title": "Current Oxygen Saturation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Monitoring_SPO2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SPO2_Monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SPO2\")\r\n  |> last()\r\n  |> yield(name: \"latest_spo2\")\r\n"
    }
   ]
  }
 ]
}